---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: resticbucket 
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://192.168.99.108:31135
    publicUrl: http://192.168.99.108:31135
